do_wandb : True
do_cli : True
n_iterations : 1000



algorithms:
  R1:
    K_number_of_clusters : 3

  R2:
    K_number_of_clusters : 3

  KMeans++:
    k : 10


datasets:
  dummy: {}
    
  iris: {}

  mnist : {}

  cifar10 : {}

  cifar100 : {}

  fashion_mnist : {}

  att : {}

  ba :
    keep_alphabets : True
    keep_digits : False

  coil: {}

  synth:
    seed : null
    n_samples : 1000
    dimension : 2
    n_clusters : 3
    proportion : [0.1, 0.2, 0.7]  # random, uniform, or list of proportions
    overlapping : True                        # not used for now
    means : [[0,1], [1,0], [1,1]]             # 'random' (N(0,I_d)), or list of means
    stds : [[0.1,0.1], [0.1,0.1], [0.1,0.1]]  # 'random' (U(min_std, max_std)), or list of stds
    min_std : 0.1
    max_std : 0.5
    pre_visualization : True             # if True, plot the data before generating the dataset in the 2D case 

metrics:
  distortion: {}

