# # For large Gaussians (10 clusters and 1000 clusters)
# name: synth
# config:
#   seed : null
#   n_samples : 10000
#   dimension : 500
#   n_clusters : 10
#   proportion : 'random' # random, uniform, or list of proportions
#   overlapping : 'none' # none, ellipsoidal, non_gaussian_laplace, non_gaussian_uniform, nested, bridging
#   means : 'random'             # 'random' which means sampled from N(0,I_d), or list of means
#   stds :   # 'random' which means sampled from U(min_std, max_std), or list of stds
#   min_std : 0.084
#   max_std : 0.094
#   pre_visualization : True
# n_classes: ${dataset.config.n_clusters}


# # For Ellipsoidal
# name: synth
# config:
#   seed : null
#   n_samples : 1000
#   dimension : 30
#   n_clusters : 10
#   proportion : 'random' # random, uniform, or list of proportions
#   overlapping : 'ellipsoidal' # none, ellipsoidal, non_gaussian_laplace, non_gaussian_uniform, nested, bridging
#   means : 'random'             # 'random' which means sampled from N(0,I_d), or list of means
#   stds :   # 'random' which means sampled from U(min_std, max_std), or list of stds
#   min_std : 0.174
#   max_std : 0.192
#   pre_visualization : True
# n_classes: ${dataset.config.n_clusters}

# For Laplace, Uniform, Nested and Bridging
name: synth
config:
  seed : null
  n_samples : 1000
  dimension : 200
  n_clusters : 10
  proportion : 'random' # random, uniform, or list of proportions
  overlapping : 'non_gaussian_laplace' # none, ellipsoidal, non_gaussian_laplace, non_gaussian_uniform, nested, bridging
  means : 'random'             # 'random' which means sampled from N(0,I_d), or list of means
  stds :   # 'random' which means sampled from U(min_std, max_std), or list of stds
  min_std : 0.13
  max_std : 0.15
  pre_visualization : True
n_classes: ${dataset.config.n_clusters}



# # Testing
# name: synth
# config:
#   seed : null
#   n_samples : 300
#   dimension : 2
#   n_clusters : 3
#   proportion : [0.1, 0.2, 0.7]  # random, uniform, or list of proportions
#   overlapping : 'nested' # none, ellipsoidal, non_gaussian_laplace, non_gaussian_uniform, nested, bridging
#   means : [[0,1], [1,0], [1,1]]             # 'random' which means sampled from N(0,I_d), or list of means
#   stds : [[0.1,0.1], [0.1,0.1], [0.1,0.1]]  # 'random' which means sampled from U(min_std, max_std), or list of stds
#   min_std : 0.1
#   max_std : 0.3
#   pre_visualization : True
# n_classes: ${dataset.config.n_clusters}