n_iterations : 10
do_tqdm : True

# Logging
do_wandb : False
wandb_config:
  project : K-means initialization Benchmark
  entity : projet13
do_tb : True
do_cli : True
to_log_in_csv:
  - distortion
  - number_of_iterations_for_convergence
  - iteration
  - number_of_iterations
  - time_training

# Metrics
metrics:
  distortion: {}
  number_of_iterations: {}

# K-means algorithm
kmeans_config:
  use_sklearn : False
  n_init : 1
  max_iter : 300
  distance_computation_method : L2
  centroid_computation_method : mean
  precompute_distances : False


# Defaults sub-configs and 
defaults:
  - _self_
  - dataset : iris
  - algo : SK_PCA_GuidedSearch
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .