n_iterations : 10
do_tqdm : True

# Logging
do_wandb : False
wandb_config:
  project : K-means initialization Benchmark
  entity : projet13
do_tb : True
do_cli : False
to_log_in_csv:
  - distortion
  - iteration
  - time_training
  - silhouette
  - calinski_harabasz
  - davies_bouldin
  # - number_of_iterations_for_convergence
  # - number_of_iterations
  # - confusion

# Metrics
metrics: all
  # number_of_iterations: {}
  # confusion: {}

# K-means algorithm
kmeans_config:
  use_sklearn : False
  n_init : 1
  max_iter : 300
  distance_computation_method : L2
  centroid_computation_method : mean
  precompute_distances : False


# Defaults sub-configs and 
defaults:
  - _self_
  - dataset : ba
  - algo : R1
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .